name: Lint

on: [push]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit black flake8 isort mypy pydocstyle pylint pytest
    - name: Analysing the code with pylint
      run: |
        pylint $(find . -iname '*.py' -not -path '*/.*')
    - name: Analysing the code with flake8
      run: |
        flake8 .
    - name: Checking security with bandit
      run: |
        bandit -r src
    - name: Checking types with mypy
      run: |
        mypy src
    - name: Checking formatting with black
      run: |
        black --check --diff .
    - name: Checking imports with isort
      run: |
        isort --check-only --diff .
    - name: Checking Docstrings with pydocstyle
      run: |
        pydocstyle --explain --source .
